### ISSUE TITLE
Benchmark Thread

### ISSUE THREAD

**Issue by aletomsic** [AntidoteDB/antidote#104]
I've created this thread for discussing evaluation results.
Please remember to describe precisely what is being tested and how. E.g., the environment (local laptop or EC2, how many machines), the kind of test (how many keys, read/write ratio, kind of objects, duration of the test, number of client threads, etc), and any other information you can think of.

**Comment by bieniusa** [comment]
Can you start with describing how to run (local) benchmarks?

**Comment by aletomsic** [comment]
I’ve not run a benchmark for a while now, maybe Li?

**Comment by marsleezm** [comment]
To run a benchmark on your local machine:
1. Do 'make rel' for antidote. Make sure that in ./rel/vars.config, the configuration for PB is like this:
{pb_ip,                 "127.0.0.1"}.
{pb_port,               "8087"}.
Then do './rel/antidote/rel/antidote console'. 
2. Go to basho_bench folder and then check the configuration of PB in ./examples/antidote_pb.config.
Make sure that the configuration for antidote_pb_port and antidote_ips have corresponding value as the above two setting. Then do './basho_bench examples/antidote_pb.config'
3. If you see any error message regarding PB interface, probably it's because the antidote_pb dependency of basho_bench is outdated. Then remove deps/antidote_pb in basho_bench and re-make.

**Comment by cmeiklejohn** [comment]
I don't really understand what workload examples/antidote_pb.config is supposed to test.  It's very low throughput in terms of ops/second and doesn't test for errors in the responses.

**Comment by marsleezm** [comment]
This is a workload created to show that dependency check is expensive for Eiger, because updating one partition after reading all partitions creates the most dependency, so the throughput of Eiger will be greatly slowed down.
I agree now there is no special reason for using it. You can change the workload to [{append,1}, {read,10}] workload.

**Comment by cmeiklejohn** [comment]
How can you guarantee with this workload you read from all partitions with random key generation?

**Comment by marsleezm** [comment]
I changed the hash function, so if a key is an integer, the corresponding object will be stored in partition[key%num_partitions]. With this trick, N consecutive integers will cover N partitions.

**Comment by cmeiklejohn** [comment]
That isn't what you previously said though.  

You said read all, and update one, which means for each iteration of the benchmark you need to read num_partiton keys (and ensure they are actually stored in different partitions) and then write to one.

**Comment by albsch** [comment]
Outdated information, I'll close this issue.
