### ISSUE TITLE
KeepAlive flag is buggy

### ISSUE THREAD

**Issue by deepthidevaki** [AntidoteDB/antidote#263]
Keepalive=true keeps transaction coord alive after a transaction commits and will be used for following transactions started by the same process. It was added as an optimization that avoids spawning new fsms for each transaction. But, when a client starts a new transaction before committing previous transaction, keepalive coordinator crashes. This happens because the coordinator in a state that cannot accept a start_transaction request.

If it has some performance benefit, we can keep it after fixing the bugs. Otherwise it should be removed.

**Comment by tcrain** [comment]
Some other issues maybe to consider in addition to performance, is that a client can start as many transactions coordinators as it wants, and also can leave them running forever.

A pool of coordinators could help for this.  Even in the case where clients are not malicious there should probably be a limit on the maximum number of transactions running concurrently as to not overload or crash the system.  Currently there is a pool of supervisors for coordinators, but they can start as many coordinators as they want.  A possibility could be to limit the number of coordinators a client could start per supervisor and limit the total number of coordinators per supervisor.  If full, each supervisor can have a list of waiting clients who want to run a transaction.  The mechanisms for implementing something like this should be straightforward.

There should also be some sort of limits imposed on how long a transaction and coordinator can live.  Two reasons I can think of are: one to avoid a client from being selfish with the coordinators, and two because a long lived transaction will have an old snapshot and will therefore be reading from old values on the disk, so it could then be easy for a client to slow down the entire system.  Adding timeouts to these should be straightforward as they are a part of the Erlang fsms, and the timeout can act like a transaction abort to the client.
