### ISSUE TITLE
What's the status of this project?

### ISSUE THREAD

**Issue by happy15** [AntidoteDB/antidote#460]
From the [news section](https://www.antidotedb.eu/news.html) on official website or the activities in this repo, it seems to me that it's lack of active development. 

What's the status of this project right now?

**Comment by bieniusa** [comment]
The news are indeed very outdated. We did quite a bit of work since 2017 as you can see in the commit logs, and consolidated the core parts in the last 2 years.
At the moment, we are planning future development and productionisation of Antidote together with [Vaxine](https://vaxine.io) as a startup. 

What's your interest in Antidote? Research, industrial use, ...? I would be interested to learn more about the community 😊

**Comment by happy15** [comment]
Thanks for the reply. We use OT for collaborative editing and meet some limit. Hence the search for better approaches. Industrial use.

**Comment by bieniusa** [comment]
I am not sure what your specific requirements regarding scalability etc. are, but there are some great CRDT platforms that specifically target collaborative editing (for a list check [here](https://crdt.tech/implementations) ).
Antidote is not primarily targeting text editing. 

@itoumlilt might also have some good pointers :)
